base_url = "http://defhacks.github.io/bookmarks"
theme = "zola.386"

default_language = "en"
title = "Bookmarks"
description = "Oh, internet."

highlight_code = true
compile_sass = true
generate_rss = true
build_search_index = false

taxonomies = [
    {name="categories", rss=false},
    {name="tags", rss=false},
]


[extra]
author = "Michael Coulter"
year = "2020"

keywords = "bookmarks"
theme_color = "#202020"
zola386_menu = [
  {path="categories", name="Categories"},
]

### THIRD PARTY
# google_analytics = "UA-012345-67"
# disqus = "disqus-user"

### SOCIAL MEDIA
#image = "https://raw.githubusercontent.com/lopes/zola.386/master/screenshot.png"
#twitter_user = "lopesoj"
#linkedin_user = "jlopesjr"
#github_user = "lopes"
# gitlab_user = ""

### I18N WORDS
label_tags = "Tags"
label_tag = "Tag"
label_categories = "Categories"
label_category = "Category"
label_author = "Author"
label_date = "Date"
label_taxonomy = "Taxonomy"
label_reading = "Reading time"
label_read_more = "Read more"
